services:
  samba-dc:
    build: .
    container_name: samba-dc
    cap_add:
      - SYS_ADMIN
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - samba-data:/var/lib/samba
      - samba-config:/etc/samba

volumes:
  samba-data:
  samba-config: